"""initial schema: hpo, diseases, cases

Revision ID: 5a2b0d847c28
Revises:
Create Date: 2026-05-11 13:57:30.094649

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a2b0d847c28"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column(
            "extracted_phenotypes", sa.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "diseases",
        sa.Column("orphanet_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("synonyms", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("inheritance_modes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("prevalence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_obsolete", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("orphanet_id"),
    )
    op.create_index(
        "ix_diseases_name_trgm",
        "diseases",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "hpo_terms",
        sa.Column("hpo_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("synonyms", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("is_obsolete", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("hpo_id"),
    )
    op.create_index(
        "ix_hpo_terms_name_trgm",
        "hpo_terms",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "disease_external_refs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("disease_id", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["disease_id"], ["diseases.orphanet_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_disease_external_refs_disease_id"),
        "disease_external_refs",
        ["disease_id"],
        unique=False,
    )
    op.create_index(
        "ix_disease_extref_lookup", "disease_external_refs", ["source", "external_id"], unique=False
    )
    op.create_index(
        "ix_disease_extref_unique",
        "disease_external_refs",
        ["disease_id", "source", "external_id"],
        unique=True,
    )
    op.create_table(
        "disease_phenotypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("disease_id", sa.String(length=20), nullable=False),
        sa.Column("hpo_id", sa.String(length=20), nullable=False),
        sa.Column("frequency", sa.String(length=50), nullable=True),
        sa.Column("frequency_numeric", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["disease_id"], ["diseases.orphanet_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hpo_id"], ["hpo_terms.hpo_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_disease_pheno_unique", "disease_phenotypes", ["disease_id", "hpo_id"], unique=True
    )
    op.create_index(
        op.f("ix_disease_phenotypes_disease_id"), "disease_phenotypes", ["disease_id"], unique=False
    )
    op.create_index(
        op.f("ix_disease_phenotypes_hpo_id"), "disease_phenotypes", ["hpo_id"], unique=False
    )
    op.create_table(
        "hpo_relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_hpo_id", sa.String(length=20), nullable=False),
        sa.Column("parent_hpo_id", sa.String(length=20), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), server_default="is_a", nullable=False),
        sa.ForeignKeyConstraint(["child_hpo_id"], ["hpo_terms.hpo_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_hpo_id"], ["hpo_terms.hpo_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_hpo_rel_unique",
        "hpo_relationships",
        ["child_hpo_id", "parent_hpo_id", "relationship_type"],
        unique=True,
    )
    op.create_index(
        op.f("ix_hpo_relationships_child_hpo_id"),
        "hpo_relationships",
        ["child_hpo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hpo_relationships_parent_hpo_id"),
        "hpo_relationships",
        ["parent_hpo_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hpo_relationships_parent_hpo_id"), table_name="hpo_relationships")
    op.drop_index(op.f("ix_hpo_relationships_child_hpo_id"), table_name="hpo_relationships")
    op.drop_index("ix_hpo_rel_unique", table_name="hpo_relationships")
    op.drop_table("hpo_relationships")
    op.drop_index(op.f("ix_disease_phenotypes_hpo_id"), table_name="disease_phenotypes")
    op.drop_index(op.f("ix_disease_phenotypes_disease_id"), table_name="disease_phenotypes")
    op.drop_index("ix_disease_pheno_unique", table_name="disease_phenotypes")
    op.drop_table("disease_phenotypes")
    op.drop_index("ix_disease_extref_unique", table_name="disease_external_refs")
    op.drop_index("ix_disease_extref_lookup", table_name="disease_external_refs")
    op.drop_index(op.f("ix_disease_external_refs_disease_id"), table_name="disease_external_refs")
    op.drop_table("disease_external_refs")
    op.drop_index(
        "ix_hpo_terms_name_trgm",
        table_name="hpo_terms",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("hpo_terms")
    op.drop_index(
        "ix_diseases_name_trgm",
        table_name="diseases",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("diseases")
    op.drop_table("cases")
    # ### end Alembic commands ###
